services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=veikkaus'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'

  veikkaus:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: unless-stopped
