package fi.veikkaus.demo.model;
// Generated Mar 20, 2025, 2:02:34 PM by Hibernate Tools 6.6.10.Final


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Event generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Event  implements java.io.Serializable {

     private Serializable id;
     private Timestamp timestamp;
     private String eventType;
     private BigDecimal amount;
     private Player playerEvents;
}


