package fi.veikkaus.demo.model;
// Generated Mar 20, 2025, 2:02:34 PM by Hibernate Tools 6.6.10.Final


import java.io.Serializable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PlayerEvent generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class PlayerEvent  implements java.io.Serializable {

     private Serializable id;
     private Player player;
     private Event event;

}


