@startuml

title Application layers

[controller] <<..controller..>> as controller
[component] <<..component..>> as component
[repository] <<..repository..>> as repository
[models] <<..models..>> as models
[dto] <<..dto..>> as dto
[pojo] <<..pojo..>> as pojo
[service] <<..service..>> as service
[config] <<..config..>> as config

' who can use configuration
controller --> config
component  --> config
repository --> config
service    --> config

' who can use pojo
controller --> pojo

' who can use dto
controller --> dto
service --> dto
component --> dto

' who can use models
repository --> models

' who can use repository
service    --> repository

' who can use component
controller --> component
service    --> component

' who can use service
controller -> service


@enduml